# Generated by Django 3.0.2 on 2021-11-28 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0003_pc'),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='fecha_pedido',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Pedido'),
        ),
        migrations.AddField(
            model_name='pc',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
