# Generated by Django 3.0.2 on 2021-12-01 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tienda', '0004_auto_20211127_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio', models.FloatField(default=0, verbose_name='Precio')),
                ('productores', models.BooleanField(default=False)),
                ('fecha_pedido', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha Pedido')),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('productos', models.ManyToManyField(to='tienda.Producto')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.DeleteModel(
            name='Pc',
        ),
    ]
