# Generated by Django 3.0.2 on 2021-12-13 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_auto_20211212_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='correo_noregistrado',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='solicitante_noregistrado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
    ]
