# Generated by Django 3.0.2 on 2021-12-13 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_auto_20211212_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='producto',
            field=models.TextField(blank=True, null=True, verbose_name='Producto'),
        ),
    ]
