# Generated by Django 3.0.2 on 2021-12-13 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0010_auto_20211212_2203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solicitud',
            old_name='correo_noregistrado',
            new_name='correo',
        ),
    ]
